from . import chatsFrame
from . import dialogFrame
from . import errorWindow
from . import loginFrame
from . import recoveryFrame
from . import regFrame
from . import tabsFrame
from . import mainWindow
from . import authWindow
