from . import chats_frame
from . import dialog_frame
from . import error_window
from . import login_frame
from . import recovery_frame
from . import reg_frame
from . import tabs_frame
from . import main_window
from . import auth_window
