from .chats_frame import *
from .dialog_frame import *
from .error_window import *
from .login_frame import *
from .recovery_frame import *
from .reg_frame import *
from .tabs_frame import *
from .main_window import *
from .auth_window import *
